#连接池
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hospital
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/

#整合mybatis
mybatis:
  type-aliases-package: com.kkb.bean #别名搜索
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true